#!/bin/sh

# Note: Use
# <https://github.com/derf/munin-plugins/blob/0743dbfacd1add7592f72bd8584461646d84a248/bananapi/bananapi_pm_voltage>
# for legacy 3.4.x kernel with sunxi patches

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	if [ -e /sys/bus/i2c/devices/0-0034/ac/voltage ]; then
		echo yes
	else
		echo no
	fi
	exit 0
fi

if [ "$1" = "config" ]; then

	echo 'graph_title BananaPi PM Voltages'
	echo 'graph_vlabel Volt'
	echo 'graph_category sensors'
	echo 'ac.label AC'
	echo 'ac.cdef ac,1000000,/'
	echo 'bat.label Battery'
	echo 'bat.cdef bat,1000000,/'
	echo 'pmu.label PMU'
	echo 'pmu.cdef pmu,1000000,/'
	echo 'vbus.label VBus'
	echo 'vbus.cdef vbus,1000000,/'

	exit 0
fi

echo ac.value "$(cat /sys/bus/i2c/devices/0-0034/ac/voltage)"
echo bat.value "$(cat /sys/bus/i2c/devices/0-0034/battery/voltage)"
echo pmu.value "$(cat /sys/bus/i2c/devices/0-0034/pmu/voltage)"
echo vbus.value "$(cat /sys/bus/i2c/devices/0-0034/vbus/voltage)"

exit 0
